import {
  Package2Icon,
  SettingsIcon,
  LogOutIcon,
  FolderIcon,
  FolderOpenIcon,
  FileIcon,
  HomeIcon,
  BookTextIcon,
  ChevronRightIcon,
  ChevronDownIcon,
  Loader2Icon,
  DownloadCloudIcon,
  XIcon,
  LinkIcon,
  FileInputIcon,
} from 'lucide-react';
import {type LucideIcon} from 'lucide-react';

export {
  MailQuestionIcon,
  BellIcon,
  Package2Icon,
  StarIcon,
  Clock3Icon,
  FolderKanbanIcon,
  HashIcon,
  FileIcon,
  FolderIcon,
  CogIcon,
  UsersIcon,
  GanttChartSquareIcon,
  LogOutIcon,
  ArrowLeft,
  ArrowUp,
  UploadCloudIcon,
  LockIcon,
  UnlockIcon,
  CircleHelpIcon,
  InfoIcon,
  FileLockIcon,
  ShieldCheckIcon,
  FolderPlusIcon,
  FolderMinusIcon,
  FilePlusIcon,
  FileMinusIcon,
  MessageCirclePlusIcon,
  MessageCircleIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  CheckIcon,
  CircleUserRound,
  ClipboardCopyIcon,
  LinkIcon,
  BookMarkedIcon,
  SunMoonIcon,
  ShieldXIcon,
  BookCheckIcon,
  BellRingIcon,
  ListIcon,
  XIcon,
  ExternalLinkIcon,
} from 'lucide-react';

export const Icons: Record<string, LucideIcon> = {
  Bucket: Package2Icon,
  Folder: FolderIcon,
  File: FileIcon,
  Home: HomeIcon,
  Settings: SettingsIcon,
  Logout: LogOutIcon,
  Readme: BookTextIcon,
  ChevronRight: ChevronRightIcon,
  ChevronDown: ChevronDownIcon,
  FolderOpen: FolderOpenIcon,
  Loader: Loader2Icon,
  Download: DownloadCloudIcon,
  Close: XIcon,
  Link: LinkIcon,
  Request: FileInputIcon,
};

export type {LucideIcon as Icon, LucideProps as IconProps} from 'lucide-react';
