export const AccessFlagLabel: Record<string, string> = {
  can_read_tree: 'Can view folders',
  can_write_tree: 'Can create folders',
  can_destroy_tree: 'Can remove folders',
  can_read_blob: 'Can view files',
  can_write_blob: 'Can write files',
  can_destroy_blob: 'Can remove files',
  can_read_bucket: 'Can view buckets',
  can_write_bucket: 'Can create buckets',
  can_destroy_bucket: 'Can remove buckets',
  can_read_comments: 'Can read comments',
  can_write_comments: 'Can write comments',
  can_download: 'Can download files',
  can_share_public: 'Can share publicly',
};
