name: "Install"
description: "Sets up Node, and installs dependencies"

inputs:
  fetch-depth:
    description: "The number of commits to fetch. 0 indicates all history for all branches and tags. 1 indicates the latest commit."
    default: "1"
    required: false
  persist-credentials:
    description: "Whether to persist credentials when fetching."
    default: "true"
    required: false
  working-directory:
    description: "Working directory to run"
    default: "."
    required: false

runs:
  using: composite
  steps:
    - name: Set up pnpm
      uses: pnpm/action-setup@v3
      with:
        package_json_file: "${{ inputs.working-directory }}/package.json"

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version-file: "${{ inputs.working-directory }}/.node-version"
        cache: pnpm
        cache-dependency-path: "${{ inputs.working-directory }}/pnpm-lock.yaml"

    - name: Install dependencies
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      env:
        HUSKY_SKIP_HOOKS: "1"
      run: |
        corepack enable
        pnpm i --ignore-scripts
