name: Quality

on:
  pull_request:
  push:
    branches:
      - "canary"
      - "main"

jobs:
  type-check:
    name: "Type Check"
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run Type Check
        run: pnpm type-check

  format-check:
    name: "Format Check"
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run Format check
        run: pnpm format-check
